version: '3.9'

services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    container_name: mysql8-db-varejo
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
      - --default_time_zone=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - /home/will/PastaCompVMs/ProjetosDataScience/ProjetoSQL/temp/mysql/db_data:/var/lib/mysql
    networks:
      - db-varejo-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_varejo
      MYSQL_USER: admindb
      MYSQL_PASSWORD: 1234567
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

networks: 
  db-varejo-network:
    driver: bridge
